spring:
  application:
    name: Student-CourseManagerSystem
  #配置数据库的链接信息
  #固定的四项信息
  datasource:
    url: jdbc:mysql://r.longfish.site:3306/student_course?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: student_course
    password: yP8#fZr@9Qk!vX2L

  #配置MyBatis的日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    mapper-locations: classpath*:com/itjay/mapper/*.xml
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: javaweb-itjay
    region: cn-beijing

server:
  address: 0.0.0.0  # 关键配置：允许外部访问
  port: 8321       # 可选：指定端口